server:
  port: ${SERVER_PORT}
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD}
    sources:
      youtube:
        enabled: true
        oauth:
          enabled: true
          accessToken: ${YOUTUBE_ACCESS_TOKEN}
          clients:
            - MUSIC
            - ANDROID_TESTSUITE
            - WEB
      soundcloud:
        enabled: true
      bandcamp:
        enabled: true
      twitch:
        enabled: true
      vimeo:
        enabled: true
      http:
        enabled: true
      local:
        enabled: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    metrics:
      prometheus:
        enabled: false
    sentry:
      dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
